apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: development
stringData:
    username: ENC[AES256_GCM,data:FUUySIENJMM=,iv:7fkKEmJ/eMp6Ia3K1c5TVrqERgeMHSXtWf/Cd7HT6ic=,tag:RMkaIyLAD/wtNf1sERs4IA==,type:str]
    password: ENC[AES256_GCM,data:ubzuJvyoyzwfpkaUEkYa,iv:4FbKKj5qRr4M9RdNbOYKwfk88lk67Tsw0OVSaLJsvA4=,tag:7p2/Tp6PZ3z8g3Ey6kWqPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16va2cdyvkrnx6ja24gkf95tgyx003van3ep4030u2z77ekjnpcmsqcn529
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMTBCbjlSSTFDUGg0ODRZ
            aGhJTlUxd3Bud3RNZFoxSXFQdERCaXlDMUJrCm9UN2ljVVFzeHR5Qmx1d1dLVFkx
            UFVCT1hGcU1aNkRLNUFKNVJHbllhdUkKLS0tICtieHp4L1ErMzQ3dGZKN1FMRkNh
            NDVQa1luSGVvQjJ2ZGFqRW5PQkk2SnMKCtTFuRtbBDCtbtAQdrOXEGCAKVqPaU+3
            6PEyOAv8sb5jg1Lxyj48F8c+zeu/+DTEiZTNw7MOZUjh4hsuhazRhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-26T03:57:33Z"
    mac: ENC[AES256_GCM,data:y6sVf94Hx3r/fZ+jMPQeLQwp8F3JWqDNmcAapvMxbiZgj5XLGON/lVNX/sOpi1SwVrqMm2y7Otm+8iOFtLvzG+QnoG6emrEdJczGAjJKPgngkEqEiuEjmi9hgM2yaKZL3JFlllUZ7o5vPT0zD9Iyob1vHzaW2o8S3xlL6qU0YOM=,iv:crLjhI4hxxGWHlUIb93yBRS46Na3UOD4lSgQl+hgNMU=,tag:rqE9e2gAXk2Odu54FGxAlA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: wakapi-user
    namespace: development
stringData:
    username: ENC[AES256_GCM,data:XEb7SXms,iv:owqWO4sXjbSU5brKDDbq72L/VLXQsvU1GuqJq6bbHpk=,tag:CRRs17G9IghOWX50lJkSAA==,type:str]
    password: ENC[AES256_GCM,data:HEPfI+3WjhQEULikugeZHw==,iv:ydcJZSnUnhNAFCEYxqcJ6BnkSEt+0P0GfXcDTpW5+GI=,tag:y0V/MxqwJSM710p5g1I6yg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16va2cdyvkrnx6ja24gkf95tgyx003van3ep4030u2z77ekjnpcmsqcn529
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMTBCbjlSSTFDUGg0ODRZ
            aGhJTlUxd3Bud3RNZFoxSXFQdERCaXlDMUJrCm9UN2ljVVFzeHR5Qmx1d1dLVFkx
            UFVCT1hGcU1aNkRLNUFKNVJHbllhdUkKLS0tICtieHp4L1ErMzQ3dGZKN1FMRkNh
            NDVQa1luSGVvQjJ2ZGFqRW5PQkk2SnMKCtTFuRtbBDCtbtAQdrOXEGCAKVqPaU+3
            6PEyOAv8sb5jg1Lxyj48F8c+zeu/+DTEiZTNw7MOZUjh4hsuhazRhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-26T03:57:33Z"
    mac: ENC[AES256_GCM,data:y6sVf94Hx3r/fZ+jMPQeLQwp8F3JWqDNmcAapvMxbiZgj5XLGON/lVNX/sOpi1SwVrqMm2y7Otm+8iOFtLvzG+QnoG6emrEdJczGAjJKPgngkEqEiuEjmi9hgM2yaKZL3JFlllUZ7o5vPT0zD9Iyob1vHzaW2o8S3xlL6qU0YOM=,iv:crLjhI4hxxGWHlUIb93yBRS46Na3UOD4lSgQl+hgNMU=,tag:rqE9e2gAXk2Odu54FGxAlA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: wakapi-token
    namespace: development
stringData:
    token: ENC[AES256_GCM,data:sM3hEiramI9XPFuOmRmUjhIO8htm8p9ujH31Vy7LOGbWTiAYOuRbPrSlC/Vod3pl,iv:EODWn28smRMLjBLpf73+1yvGzXqUgDBNfqfEi6DfmeA=,tag:ZLNtUbL02E7JnNtTlahGsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16va2cdyvkrnx6ja24gkf95tgyx003van3ep4030u2z77ekjnpcmsqcn529
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMTBCbjlSSTFDUGg0ODRZ
            aGhJTlUxd3Bud3RNZFoxSXFQdERCaXlDMUJrCm9UN2ljVVFzeHR5Qmx1d1dLVFkx
            UFVCT1hGcU1aNkRLNUFKNVJHbllhdUkKLS0tICtieHp4L1ErMzQ3dGZKN1FMRkNh
            NDVQa1luSGVvQjJ2ZGFqRW5PQkk2SnMKCtTFuRtbBDCtbtAQdrOXEGCAKVqPaU+3
            6PEyOAv8sb5jg1Lxyj48F8c+zeu/+DTEiZTNw7MOZUjh4hsuhazRhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-26T03:57:33Z"
    mac: ENC[AES256_GCM,data:y6sVf94Hx3r/fZ+jMPQeLQwp8F3JWqDNmcAapvMxbiZgj5XLGON/lVNX/sOpi1SwVrqMm2y7Otm+8iOFtLvzG+QnoG6emrEdJczGAjJKPgngkEqEiuEjmi9hgM2yaKZL3JFlllUZ7o5vPT0zD9Iyob1vHzaW2o8S3xlL6qU0YOM=,iv:crLjhI4hxxGWHlUIb93yBRS46Na3UOD4lSgQl+hgNMU=,tag:rqE9e2gAXk2Odu54FGxAlA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
