{
 "title": "ErlangVM",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(erlang_vm_process_count, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Process",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_process_count{instance=\"$host\"}",
     "legendFormat": "Process count"
    },
    {
     "expr": "erlang_vm_statistics_run_queues_length_total{instance=\"$host\"}",
     "legendFormat": "Run queue length"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_threads{instance=\"$host\"}",
     "legendFormat": "Threads"
    },
    {
     "expr": "erlang_vm_thread_pool_size{instance=\"$host\"}",
     "legendFormat": "Thread pool size"
    }
   ]
  },
  {
   "title": "Memory system",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_memory_system_bytes_total{instance=\"$host\"}",
     "legendFormat": "{{usage}}"
    }
   ]
  },
  {
   "title": "Memory processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_memory_processes_bytes_total{instance=\"$host\"}",
     "legendFormat": "{{usage}}"
    }
   ]
  },
  {
   "title": "ETS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_ets_tables{instance=\"$host\"}",
     "legendFormat": "ETS tables"
    },
    {
     "expr": "erlang_vm_ets_limit{instance=\"$host\"}",
     "legendFormat": "ETS limit"
    },
    {
     "expr": "erlang_vm_dets_tables{instance=\"$host\"}",
     "legendFormat": "DETS tables"
    }
   ]
  },
  {
   "title": "Mnesia",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "erlang_mnesia_lock_queue{instance=\"$host\"}",
     "legendFormat": "Lock queue"
    },
    {
     "expr": "erlang_mnesia_held_locks{instance=\"$host\"}",
     "legendFormat": "Held locks"
    }
   ]
  }
 ]
}