---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
configMapGenerator:
  - name: loki-grafana-dashboards
    files:
      - dashboard/loki-dashboard.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/component: monitoring
