apiVersion: v1
kind: Secret
metadata:
    name: spotify-mongodb-password
    namespace: default
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:LG3qe6+RON9PZWDK10VdXfDfkkg=,iv:gmeW83kw1BGpWeKcC0JIkQ4Kc4AM2EtXWAb+MWheP/8=,tag:MituHQMDjy3sXuQg0saf7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16va2cdyvkrnx6ja24gkf95tgyx003van3ep4030u2z77ekjnpcmsqcn529
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTVdRVUUydDZZR1RKdlNP
            NWp3cjN4eUdOdmdrVUVJUDdmS2N1MVBWUVZzCkkzcE5tb2tvVEJDbS9QZDRLNlZ6
            blE1SVZsaHhtTlczS1AxaGlrbU80dlUKLS0tIGhrVXgwZEpjbDlBZFduU1RYSkNJ
            MWROVFdzUjZIazVVTWkwTlIxSEZqNk0Kghe+EkhWy1N7WjQaVFnHZQRE7g1cm8cD
            TZ+SAJ+62vko/yoaxt0AtcEZNcyOGZn6UXZJb6Poe4skaHn95LBZtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-24T23:39:49Z"
    mac: ENC[AES256_GCM,data:bkaEEqyRNrCcUUMUhJgfqQSpcmP/U2C0sPYZs5TbsKvdltereMpmUnwNQZyuAjxKGESSt2Iavz5smVQNxbB+uROwh4VB57WaiIkKXQjIs4ZbeQrVbTErfh6rA0+K2WsTJBaIW4CfyQAj7DPXOTkb/6jCBEU1r5z0Y/Oxd+aQip8=,iv:XHzOhRaH8EH+UgwMcJJ32w0p83alJVXFRKiXsHZVQhk=,tag:yXJpCXNunWOvkQW+gIB0jg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: prometheus-endpoint-password
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:rxMYsHrl/nACrg==,iv:vXb9g2HmvFKeUv3G11dQJxNfT1Sf0GhqNUhr6CHvrq8=,tag:WypXxEBnr4Nvc81SKprK7Q==,type:str]
    password: ENC[AES256_GCM,data:MpOqU/1eLrK98XIzMSWV,iv:y5Hw/VpLS98fVZJkwsTKAYdc4UWV61TifvCqd8AT9HY=,tag:czBdG8GhNbn6y/TSWL0Y1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16va2cdyvkrnx6ja24gkf95tgyx003van3ep4030u2z77ekjnpcmsqcn529
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTVdRVUUydDZZR1RKdlNP
            NWp3cjN4eUdOdmdrVUVJUDdmS2N1MVBWUVZzCkkzcE5tb2tvVEJDbS9QZDRLNlZ6
            blE1SVZsaHhtTlczS1AxaGlrbU80dlUKLS0tIGhrVXgwZEpjbDlBZFduU1RYSkNJ
            MWROVFdzUjZIazVVTWkwTlIxSEZqNk0Kghe+EkhWy1N7WjQaVFnHZQRE7g1cm8cD
            TZ+SAJ+62vko/yoaxt0AtcEZNcyOGZn6UXZJb6Poe4skaHn95LBZtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-24T23:39:49Z"
    mac: ENC[AES256_GCM,data:bkaEEqyRNrCcUUMUhJgfqQSpcmP/U2C0sPYZs5TbsKvdltereMpmUnwNQZyuAjxKGESSt2Iavz5smVQNxbB+uROwh4VB57WaiIkKXQjIs4ZbeQrVbTErfh6rA0+K2WsTJBaIW4CfyQAj7DPXOTkb/6jCBEU1r5z0Y/Oxd+aQip8=,iv:XHzOhRaH8EH+UgwMcJJ32w0p83alJVXFRKiXsHZVQhk=,tag:yXJpCXNunWOvkQW+gIB0jg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: spotify-creds
    namespace: default
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:QIjtJievqvT/fzS5e5vpNdZ/a+esJeveu5jtITlrw+w=,iv:dJiGKkgJEU808Sdt1VbyT4giXVZxZq63RKjxX4Mk51Q=,tag:x4QKSzDT9SZg1JfL032lQA==,type:str]
    client-secret: ENC[AES256_GCM,data:6HbyKVprADPcUY6m4g6u6FzyHsm3NpZY516Sq9S66Bs=,iv:qrM1zbDBN0FaCuAV09UcaMDXmqQbefNerBHQG7RR/PI=,tag:M7ycgXdJ/gKITHDgZLAISw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16va2cdyvkrnx6ja24gkf95tgyx003van3ep4030u2z77ekjnpcmsqcn529
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTVdRVUUydDZZR1RKdlNP
            NWp3cjN4eUdOdmdrVUVJUDdmS2N1MVBWUVZzCkkzcE5tb2tvVEJDbS9QZDRLNlZ6
            blE1SVZsaHhtTlczS1AxaGlrbU80dlUKLS0tIGhrVXgwZEpjbDlBZFduU1RYSkNJ
            MWROVFdzUjZIazVVTWkwTlIxSEZqNk0Kghe+EkhWy1N7WjQaVFnHZQRE7g1cm8cD
            TZ+SAJ+62vko/yoaxt0AtcEZNcyOGZn6UXZJb6Poe4skaHn95LBZtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-24T23:39:49Z"
    mac: ENC[AES256_GCM,data:bkaEEqyRNrCcUUMUhJgfqQSpcmP/U2C0sPYZs5TbsKvdltereMpmUnwNQZyuAjxKGESSt2Iavz5smVQNxbB+uROwh4VB57WaiIkKXQjIs4ZbeQrVbTErfh6rA0+K2WsTJBaIW4CfyQAj7DPXOTkb/6jCBEU1r5z0Y/Oxd+aQip8=,iv:XHzOhRaH8EH+UgwMcJJ32w0p83alJVXFRKiXsHZVQhk=,tag:yXJpCXNunWOvkQW+gIB0jg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
