---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongodb-service-monitor
  namespace: default
spec:
  endpoints:
    - basicAuth:
        password:
          key: password
          name: prometheus-endpoint-password
        username:
          key: username
          name: prometheus-endpoint-password
      port: prometheus
      scheme: http
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: mongodb-svc
