---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: your-spotify-mongodb
  namespace: default
spec:
  members: 1
  type: ReplicaSet
  version: "5.0.6"

  prometheus:
    username: prometheus
    passwordSecretRef:
      name: prometheus-endpoint-password

  security:
    authentication:
      modes: ["SCRAM"]

  users:
    - name: eslack
      db: your-spotify
      passwordSecretRef:
        name: spotify-mongodb-password
      roles:
        - name: readWrite
          db: your-spotify
      scramCredentialsSecretName: my-scram
