version: "3.9"

services:
  caddy:
    image: iarekylew00t/caddy-cloudflare:latest
    container_name: caddy
      #command: /usr/bin/caddy run --resume
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "2019:2019" # admin
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=${DOMAIN}
      - CF_API_TOKEN=${CF_API_TOKEN}
      - NUBUNTU_ADDR=${NUBUNTU_ADDR}
      - KUBUNTU_ADDR=${KUBUNTU_ADDR}
      - TORRR_ADDR=${TORRR_ADDR}
      - MON_ADDR=${MON_ADDR}
      - RASPI_ADDR=${RASPI_ADDR}
      - GATEWAY_ADDR=${GATEWAY_ADDR}
      - VED_ADDR=${VED_ADDR}

  caddy-ui:
    image: qmcgaw/caddy-ui
    container_name: caddy-ui
    ports:
      - 8443:8000/tcp
    environment:
      - CADDY_API_ENDPOINT=http://caddy:2019

volumes:
  caddy_data:
  caddy_config:
