---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.33.1.234
  share: /mnt/share/apps/PVCs
reclaimPolicy: Delete
volumeBindingMode: Immediate
# mountOptions:
#   - nfsvers=4.1
