---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: storage
spec:
  interval: 15m
  chart:
    spec:
      chart: minio
      version: 4.0.15
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2022-09-25T15-44-53Z
    mode: standalone
    ignoreChartChecksums: true
    rootUser: "${SECRET_MINIO_ROOT_USER}"
    rootPassword: "${SECRET_MINIO_ROOT_PASSWORD}"
    drivesPerNode: 1
    replicas: 1
    persistence:
      enabled: true
      existingClaim: minio-nfs
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
      path: /
      hosts:
        - &host-api "s3.${SECRET_DOMAIN}"
      tls:
        - secretName: minio-tls
          hosts:
            - *host-api

    consoleIngress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
      path: /
      hosts:
        - &host-console "minio.${SECRET_DOMAIN}"
      tls:
        - secretName: minio-console-tls
          hosts:
            - *host-console
    users: []
    environment:
      TZ: "${TIMEZONE}"
      MINIO_UPDATE: "off"
      # MINIO_PROMETHEUS_JOB_ID: "minio"
      # MINIO_PROMETHEUS_URL: "http://thanos-query.monitoring:9090"
      MINIO_SERVER_URL: "https://s3.${SECRET_DOMAIN}"
    metrics:
      serviceMonitor:
        enabled: true
        public: true
    resources:
      requests:
        memory: 500Mi
        cpu: 100m
      limits:
        memory: 1000Mi
