version: "3.7"
services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    image: semitechnologies/weaviate:1.18.3
    ports:
      - 8081:8080
    restart: unless-stopped
    container_name: weaviate
    environment:
      IMAGE_INFERENCE_API: "http://i2v-neural:8080"
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "img2vec-neural"
      ENABLE_MODULES: "img2vec-neural"
      CLUSTER_HOSTNAME: "node1"
    volumes:
      - ./weaviate-data:/var/lib/weaviate

  i2v-neural:
    image: semitechnologies/img2vec-pytorch:resnet50
    ports:
      - 8082:8080
    restart: unless-stopped
    container_name: i2v-neural
    environment:
      ENABLE_CUDA: "0"
