apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  releaseName: podinfo
  chart:
    spec:
      chart: podinfo
      version: 6.8.0
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  interval: 60m
  install:
    remediation:
      retries: 3
  values:
      replicaCount: 2
      ui:
        color: "#34577c"
        message: "hello from slacknet"
      service:
        enabled: true
        type: ClusterIP
      ingress:
        enabled: true
        className: internal
        annotations: 
          kubernetes.io/tls-acme: "true"
          external-dns.alpha.kubernetes.io/hostname: podinfo.local.eslack.net
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/use-proxy-protocol: "false"
        hosts:
          - host: podinfo.local.eslack.net
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - podinfo.local.eslack.net
            secretName: acme-crt-secret-prod
