version: "3.7"
services:
  adguardhome:
    # image: adguard/adguardhome
    image: adguard/adguardhome:v0.107.48
    container_name: adguardhome
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./conf:/opt/adguardhome/conf
      - ./work:/opt/adguardhome/work
    ports:
      # DNS
      - 53:53/tcp
      - 53:53/udp
      # HTTPS
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
      - 3001:3000/tcp

networks:
  default:
    external: true
    name: adguard
