
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text-to-speech
tts:
  - platform: google_translate

recorder:
  purge_keep_days: 30
  db_url: !secret db_url

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 10.33.1.0/24
    - 192.168.0.0/16
    - 10.99.70.2
    - 172.22.0.2

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Enable prom metrics with prefix `hass`
prometheus:
  namespace: hass
