apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: security
stringData:
    username: ENC[AES256_GCM,data:PhimfFHERsQ=,iv:xd62G71lUNYj2pVvocbQYNuR/V8Vts1QIvyT8wsXvnE=,tag:9izwjE18Y/jRR0JtD5cpzw==,type:str]
    password: ENC[AES256_GCM,data:0lvJd1E3wMmcM3o1fMcv,iv:pMWx7GTnJXHV/h72VGs69OE9JP5GRVttP38zHI14pd0=,tag:iFJmcQmNFBQlKzZfrn63JA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16va2cdyvkrnx6ja24gkf95tgyx003van3ep4030u2z77ekjnpcmsqcn529
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNkNaa2JXNklHU1UvbHlW
            MUxEWUJkYU5iVkpUd1lZeVIwSUF6TWM4WkdzCkRFT2hBNDhNSDdUVmFNak5hZTVE
            RzlnZjNwbWVOZHJxdUJGbDlZd05JTjAKLS0tIEJwd1VMWmlMeU40SjBqUjlnLzlx
            ZzF1MGhYL1RqMmZWVUJ3SERZWUdkRDgKkI5jak/Gmti9aNqYYhHm5mn6fUtXjBK5
            S69mPqgbj2lpjg6ZWGLEb+2cNQFWFIKZkyrXrnMjRImwRLbWvLxXFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-26T03:59:51Z"
    mac: ENC[AES256_GCM,data:ZdveFvWIL36WZ/TstZs+su+AJuDeCH0TeFYIow3WR3nZPf1MJntryx80grkArMepW/3YxNghbrRgUNwUVchZQcLLegFHVneZxEbvH1EAS/lL0LI2aXWoUqAzwbP2/NmOH2ZGSR1blLz1Umh8fh/o0Pl6ABwHT9ucdgYy+8lNHsI=,iv:Z8VEDZG+wAYceMirtfuSAPHoA8hkUTt4lPO/RNqeGSk=,tag:Igan4wY0yxGA/QoAw2n8gg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: vaultwarden-user
    namespace: security
stringData:
    username: ENC[AES256_GCM,data:KW3MeXwsg2sd5ds=,iv:BLmEhgp1M3+SycUoCoRG2ST8v6RExdlsJNy1Ez3RbFw=,tag:i2POmtKZajZvxAEIH9SXjg==,type:str]
    password: ENC[AES256_GCM,data:7WgQbXeuVGp0+eEHSZXs,iv:WpVzqIRlAkftlnucm06NO/L7p3FJrPF27cQKFr5r3ZU=,tag:AcYNk1XLpDP/YnnkotJf5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16va2cdyvkrnx6ja24gkf95tgyx003van3ep4030u2z77ekjnpcmsqcn529
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNkNaa2JXNklHU1UvbHlW
            MUxEWUJkYU5iVkpUd1lZeVIwSUF6TWM4WkdzCkRFT2hBNDhNSDdUVmFNak5hZTVE
            RzlnZjNwbWVOZHJxdUJGbDlZd05JTjAKLS0tIEJwd1VMWmlMeU40SjBqUjlnLzlx
            ZzF1MGhYL1RqMmZWVUJ3SERZWUdkRDgKkI5jak/Gmti9aNqYYhHm5mn6fUtXjBK5
            S69mPqgbj2lpjg6ZWGLEb+2cNQFWFIKZkyrXrnMjRImwRLbWvLxXFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-26T03:59:51Z"
    mac: ENC[AES256_GCM,data:ZdveFvWIL36WZ/TstZs+su+AJuDeCH0TeFYIow3WR3nZPf1MJntryx80grkArMepW/3YxNghbrRgUNwUVchZQcLLegFHVneZxEbvH1EAS/lL0LI2aXWoUqAzwbP2/NmOH2ZGSR1blLz1Umh8fh/o0Pl6ABwHT9ucdgYy+8lNHsI=,iv:Z8VEDZG+wAYceMirtfuSAPHoA8hkUTt4lPO/RNqeGSk=,tag:Igan4wY0yxGA/QoAw2n8gg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
