---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-tunnel-deployment
  labels:
    app: cloudflare-tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-tunnel
  template:
    metadata:
      labels:
        app: cloudflare-tunnel
    spec:
      containers:
        - name: cloudflare-tunnel
          image: erisamoe/cloudflared
          command: ["tunnel run"]
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 400m
              memory: 512Mi
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-tunnel-creds
                  key: TUNNEL_TOKEN
                  optional: false
      restartPolicy: Always
