apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudflare-tunnel-creds
    namespace: networking
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:7NxOAW6RWN2C1jCMBUdhuo4vQtxQIa+Di4Ce41OmoQjwUxyXbwchRr9OXonNbpQan56ASgHJND/Z1uhtboDm7JNknPVKgOOgc3tshNlIwPKxgzQDAr7lRHbZg+DHz6ecVQa4Udtgk/pgA/nva82jJJn2CwZnT6KM0ABfvx8qA8dOIjCYvSNBgG7k5pv2DWyLiEbrxIFN8jHt46yEfx4+4YtDVFXDD0MqhMJlhBlEPidnS5Nna00SKw==,iv:cqJBes+GtK5jZSFj8WXJKyEZvX+cmAHrrDI2nVpVNe4=,tag:jCIZj/UqwxeJDKrIWzQ1WQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16va2cdyvkrnx6ja24gkf95tgyx003van3ep4030u2z77ekjnpcmsqcn529
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZXpqM2FyT3JuZUMwSFNZ
            bm5ZNmwrZ09UQ1ZOQ2hTUkE3eWlOVFJFWEhzClVOUWVWY2ZXd3lETmhFd1lJT0lT
            QTJ6YjR0L2lVbDIyOFVYWGdtY3lpc1EKLS0tIExYZUJhaFhHRFpmUHFvZENsaFBs
            Y2Y5V0FKdlJwRExXdW1ZRmdQbDB4aDgKcmn0I4T4fYUQcqoV9hartxDEZPs/jZuX
            J5XPEqa3i9WmqI3hDv3XHE4HNzR++zXhKammaNEQx9pPqONP/OfIgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-25T23:28:58Z"
    mac: ENC[AES256_GCM,data:W5ZvLZHfu/OCEUvK1B8kGFe9M8ZsClPYVl/Gs7BxgGUBTGg80/P5YGhlMbmeVudwArLl/cAH4lEQNdcxXnsvBvb8AnrhszedIAftvbNUCQmDvipJiT9BAhRNmmRsAtGmG7jLOOZQB1eJyz2nqx3j5vqBbWjwxWUzXfqUKasKPxQ=,iv:kR+fjiS7IAaZCHOtkakZqFbZSeCJOR+S5/RD4rhoPXs=,tag:J/bWoaHfZkaLy2PMURPdMw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
