---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: speedtest-exporter-monitor
  namespace: monitoring
  labels:
    app: speedtest-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: speedtest-exporter
      app.kubernetes.io/name: speedtest-exporter
  endpoints:
    - port: metrics
      path: '/metrics'
      interval: 60m
      scrapeTimeout: 2m
