---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: 1.16.1
      sourceRef:
        name: external-dns
        kind: HelmRepository
        namespace: flux-system
  values:
    crd:
      create: true
    interval: 2m
    provider:
      name: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns-secrets
            key: cloudflare-api-token
    policy: sync
    sources:
      - ingress
      - service
      - crd
