apiVersion: kustomize.toolkit.fluxcd.io/v2
kind: Kustomization
metadata:
  name: metallb-crd
  namespace: flux-system
spec:
  interval: 15m
  dependsOn: 
  - name: metallb
  path: ./crd
  prune: true 
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: metallb-controller
      namespace: metallb
