apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: bgp-pool
  namespace: metallb
spec:
  addresses:
    - 10.33.20.50-10.33.20.70
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgp-pool
  namespace: metallb
