apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  interval: 1h
  chart:
    spec:
      chart: metallb
      version: 0.14.9
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      interval: 1h
  install:
    createNamespace: true
    remediation:
      retries: 3
  crds: CreateReplace
  values:
    speaker:
      frr:
        enabled: false
