apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-resources
  namespace: flux-system
spec:
  interval: 15m
  dependsOn: 
  - name: metallb
  path: ./clusters/cluster/apps/metallb/resources
  prune: true 
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: metallb-controller
      namespace: metallb

