---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reverse-proxy
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: reverse-proxy
      version: 2.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      replicas: 1
    # generateTLS:
    #   enabled: true
    #   secretName: ""

    instances:
      - name: proxmox
        enabled: true
        ip: 10.33.1.174
        port: 8006
        ingress:
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-staging"
            hajimari.io/enable: "true"
            hajimari.io/icon: "speedometer"
            nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
          tls:
            - hosts:
                - proxmox.local.${SECRET_DOMAIN}
              secretName: "proxmox-tls"
          hosts:
            - host: proxmox.local.${SECRET_DOMAIN}
              path: /

    ingressPort:
      # -- Ingress port for non-TLS
      http: 80
      # -- Ingress port for TLS
      tls: 443

    connectionTest:
      # -- seconds to wait before next retry
      waitretry: 2
      # -- second to wait in case no data is received and then try again
      readtimeout: 2
      # -- tries to connect
      tries: 30
