{
 "title": "Wakapi Dashboard",
 "description": "Prometheus wakatime_exporter",
 "tags": [
  "prometheus",
  "wakapi"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "top10lang",
    "query": {
     "query": "query_result(topk(10, sum without (instance,job) (increase(wakatime_language_seconds_total{name!=\"Other\"}[$__range])) > 0))"
    }
   },
   { "name": "longterm", "label": "Long Term Interval", "query": "1d,7d,14d,30d,60d,120d" }
  ]
 },
 "panels": [
  {
   "title": "Time Logged",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance) (wakatime_cumulative_seconds_total)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Machine",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without (instance) (increase(wakatime_machine_seconds_total[$__range])) > 0",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "OS",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without (instance) (increase(wakatime_operating_system_seconds_total[$__range])) > 0",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Language Distribution",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, sum without (instance) (increase(wakatime_language_seconds_total{name!=\"Other\"}[$__range])) > 0)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Heartbeats",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wakatime_heartbeats_total" }
   ]
  },
  {
   "title": "History",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without (instance) (increase(wakatime_seconds_total[1d]))",
     "legendFormat": "time"
    },
    {
     "expr": "sum without (instance) (increase(wakatime_seconds_total[$__interval]))",
     "legendFormat": "activity"
    }
   ]
  },
  {
   "title": "Language Distribution",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wakatime_language_seconds_total",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Time by Project",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without (instance) (increase(wakatime_project_seconds_total[1d]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Time by Language",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without (instance) (increase(wakatime_language_seconds_total[1d]))",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}