# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:943+4O6HRhix88LkHxfrS6qCHNjzQcQFc4LhsNt1S2ejw3jM7Q==,iv:uiQQXAXcE+8A8708EfMS2HXJTh8fbmIN+zQ3sSUr+dQ=,tag:BuNiN9tPOUbZY1W6lbzAOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16va2cdyvkrnx6ja24gkf95tgyx003van3ep4030u2z77ekjnpcmsqcn529
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBheFRHMERZM0phZVVDK0kx
            SEl1QU1MaWxNaXRucHJiYTZvamdyTWFSVWdFCkpDakdmaXovT2h6d1ZUOWpkODht
            YmNZRHFidi8wdzBKdjdnZitNaE4wK3cKLS0tIGpYdEVrRlR4Tk5OckN6TDRDY1NW
            azNHekoyblpIUjBpVVBIZkRJZDB0blEK+VAeR+x/UVfSgnWRTNow/5mbO2SNfQyk
            IBGlVhKzhSBssIyWJmLcBpV9xtCDbG20JFs35JuCgYjYLRSqcvHF6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-12T00:09:12Z"
    mac: ENC[AES256_GCM,data:0bmh1eK0AxQvmbNJETHlE2Ivc0/P5/oP39GzP40sO8o4Dde+Q4Zg63lwDoVXjucc5bQQgiDd7HC+ZK+sY8Iss3Aka+TrnosUY7giRYQfkbMSoVZBqyeNW90uxCtHLab0g7C4B5r10qDVIuXB8cMzypHwIF9K3lIiZGjc7vkyOts=,iv:TBOQ2N0UxVRTu8XmI2YyL1m+91zf8A/AuevB8fG1kgY=,tag:WBKx4Vr5+su+XSR+Bcp1AQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
