---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/New_York
  METALLB_LB_RANGE: 10.33.1.80-10.33.1.89
  METALLB_K8S_GATEWAY_ADDR: 10.33.1.80
  METALLB_INGRESS_ADDR: 10.33.1.81
