---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home-automation
spec:
  interval: 15m
  chart:
    spec:
      chart: mosquitto
      version: 4.8.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 15m
  values:
    image:
      repository: eclipse-mosquitto
      tag: 2.0.14
    env:
      TZ: ${TIMEZONE}
    auth:
      enabled: true
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${METALLB_MOSQUITTO_ADDR}"
        externalTrafficPolicy: Local
        ports:
          mqtt:
            enabled: true
            port: 1883
            protocol: TCP
            targetPort: 1883
    podAnnotations:
      secret.reloader.stakater.com/reload: mosquitto-config
    persistence:
      data:
        enabled: true
        existingClaim: mosquitto-data
      configinc:
        enabled: true
        type: custom
        volumeSpec:
          secret:
            secretName: mosquitto-config

    mqtt-cert:
      enabled: false
      # enabled: true
      # mountPath: /cert
      # type: secret
      # name: mqtt-cert

    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        memory: 124M
