---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ceph-csi-cephfs-secret
  namespace: storage
spec:
  target:
    name: csi-cephfs-secret
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashi-vault
  data:
    - secretKey: userID
      remoteRef:
        key: ceph
        property: cephfs-user-id
    - secretKey: userKey
      remoteRef:
        key: ceph
        property: cephfs-user-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ceph-csi-rbd-secret
  namespace: storage
spec:
  target:
    name: csi-rbd-secret
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashi-vault
  data:
    - secretKey: userID
      remoteRef:
        key: ceph
        property:  rbd-user-id
    - secretKey: userKey
      remoteRef:
        key: ceph
        property:  rbd-user-key
