apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ceph-csi-rbd
spec:
  interval: 30m
  timeout: 5m
  chart:
    spec:
      chart: ceph-csi-rbd
      version: 3.14.0
      sourceRef:
        kind: HelmRepository
        name: ceph-csi
        namespace: flux-system
      interval: 5m
  # https://github.com/ceph/ceph-csi/blob/devel/charts/ceph-csi-rbd/values.yaml
  values:
    csiConfig:
      - clusterID: "2cc35365-6eff-44ee-820e-4769e1a430e5" # fsid
        monitors:
          - 10.33.32.10:6789
          - 10.33.32.11:6789
          - 10.33.32.12:6789

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ceph-csi-cephfs
spec:
  interval: 30m
  timeout: 5m
  chart:
    spec:
      chart: ceph-csi-cephfs
      version: 3.14.0
      sourceRef:
        kind: HelmRepository
        name: ceph-csi
        namespace: flux-system
      interval: 5m
  # https://github.com/ceph/ceph-csi/blob/devel/charts/ceph-csi-cephfs/values.yaml
  values:
    csiConfig:
      - clusterID: "2cc35365-6eff-44ee-820e-4769e1a430e5" # fsid
        monitors:
          - 10.33.32.10:6789
          - 10.33.32.11:6789
          - 10.33.32.12:6789
        cephFS:
          subvolumeGroup: ""
    pluginConfig:
      cephFS:
        mountTool: "fuse"
