---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mqtt-exporter
  namespace: home-automation
spec:
  interval: 15m
  chart:
    spec:
      chart: mqtt-exporter
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 15m
  values:
    env:
      TZ: ${TIMEZONE}
      LOG_LEVEL: INFO
      MQTT_ADDRESS: ${METALLB_MOSQUITTO_ADDR}
      MQTT_PORT: 1883
      MQTT_TOPIC: "#"
      MQTT_KEEPALIVE: 60
      # MQTT_USERNAME: see valuesFrom below
      # MQTT_PASSWORD: see valuesFrom below
      PROMETHEUS_PORT: 9000
      PROMETHEUS_PREFIX: mqtt_exporter_
      TOPIC_LABEL: topic
      ZIGBEE2MQTT_AVAILABILITY: "False"
    service:
      main:
        ports:
          http:
            port: 9000
    metrics:
      enabled: true
      serviceMonitor:
        interval: 30s
        scrapeTimeout: 10s
        labels: {}
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 65534
  valuesFrom:
    - secretKeyRef:
      name: mqtt-exporter-config
      namespace: home-automation
      key: MQTT_USERNAME
      optional: false
    - secretKeyRef:
      name: mqtt-exporter-config
      namespace: home-automation
      key: MQTT_PASSWORD
      optional: false
