apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: mqtt-exporter-config
    namespace: home-automation
data:
    values.yaml: ENC[AES256_GCM,data:0kL7wXAAst0uQjtb1Xg9DN0BZwpARJlbxIpWcsUVdjbUwBxiMOqkXSPXXNAZVTjX6P45rjIaf/BEHQ==,iv:5pkBYPQXSx2tvQzgvrGAkQg3gHKePfONbYyk46qVGIo=,tag:dxM3NeV98bemtYD6Z8TlEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16va2cdyvkrnx6ja24gkf95tgyx003van3ep4030u2z77ekjnpcmsqcn529
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiK2RkTTJvQy9PcE5vSm5w
            REpmUFJpMFRWakRKTmlOdmlKZlFzOHdoZHljCi82bkNJczBzUVI5WXZ2MkY5bXVm
            WXdSdmpHckwvQUZVZkYwMVo2dmVyUjAKLS0tIGYwL2R1V3JVbzJKTy9VWXUyZGwx
            Q1pVekpMWERuNkFsNXgwbVJ5R1F1Z28Km3b4qNBY3Bv9PiSmtEoeTcHJuHD8FTtl
            k+e7Ef1yJ8XJbJ1FUAGN69awaN/ki4ezKR9j/H49D4JqW5UozyPwvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-15T17:13:39Z"
    mac: ENC[AES256_GCM,data:dBziVn3iXuHsPs+j7SXWpVv1RLFBMdbfqeFUMZHRTmbAhdl4SWNgysDsJQgY4As/mYi0ZvV6h1qw1jlnK3nGtL5vpeLDmffH9iK93MtJBv7xX+trC0HRUMoZFAKPUxaB+O5gDbFC3YDxVCvnjrFn4hfnii/1B/RNMoqxxrHB2Ng=,iv:LJAuDzBm9CLUa2N3iy8PzbHOmPWLa1wxENrk82lzcJA=,tag:43t9Rop6eNwAaYPXVYrgmA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
