groups:
- name: InstanceHealth
  rules:

  - alert: service_down
    expr: up == 0
    for: 10m
    labels:
      severity: critical
    annotations:
      value: DOWN ({{ $value }})
      title: 'Instance {{ $labels.instance }} down'
      description: '{{ $labels.instance }} of job {{ $labels.job }} is unavaliable'
