groups:
- name: InstanceHealth
  rules:

  - alert: heartbeat
    expr: vector(1)
    labels:
      event: "heartbeat"
      severity: "critical"
      timeout: "120"
    annotations:
      summary: "heartbeat from prometheus"
      description: "heartbeat from from prometheus"

  - alert: service_down
    expr: up == 0
    for: 5m
    labels:
      severity: critical
      correlate: service_up,service_down
    annotations:
      value: DOWN ({{ $value }})
      title: 'Instance {{ $labels.instance }} down'
      description: '{{ $labels.instance }} of job {{ $labels.job }} is unavaliable'

  - alert: service_up
    expr: up == 1
    labels:
      severity: normal
      correlate: service_up,service_down
    annotations:
      value: UP ({{ $value }})
      title: 'Instance {{ $labels.instance }} up'
      description: '{{ $labels.instance }} of job {{ $labels.job }} is avaliable'
