---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - helm-release.yaml
configMapGenerator:
  - name: cloudflare-proxied-networks
    files:
      - cloudflare-proxied-networks.txt
  - name: nginx-exporter-grafana-dashboard
    files:
      - dashboards/nginx.json
      - dashboards/request-handling.json
    options:
      labels:
        grafana_dashboard: "1"
generatorOptions:
  disableNameSuffixHash: true
