version: "3.7"
services:
  prometheus:
    image: prom/prometheus:v2.36.2
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./config:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--log.level=info'
    ports:
      - 9090:9090

volumes:
  prometheus-data:

networks:
  default:
    external: true
    name: mon
