---
kind: Service
apiVersion: v1
metadata:
  name: mosquitto-exporter-service
  labels:
    app: mosquitto-exporter
spec:
  selector:
    app: mosquitto-exporter
  ports:
    - name: metrics
      port: 9234
