---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wakapi-config
  namespace: development
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
