---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app wakapi
  namespace: development
spec:
  releaseName: *app
  interval: 15m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: cloudnative-pg
      namespace: database
  values:
    global:
      nameOverride: *app
    image:
      repository: ghcr.io/muety/wakapi
      tag: latest
    env:
      WAKAPI_DB_TYPE: "postgres"
      WAKAPI_DB_NAME: "wakapi"
      WAKAPI_DB_USER: "wakapi"
      WAKAPI_DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: wakapi-user
            key: password
      WAKAPI_DB_HOST: "PG_DATABASE_RW_SERVICE_HOST"
      WAKAPI_DB_PORT: 5432
      WAKAPI_DB_SSL: true
      ENVIRONMENT: "prod"
      WAKAPI_PASSWORD_SALT: "saltyboi"
      WAKAPI_EXPOSE_METRICS: true
      WAKAPI_PUBLIC_URL: &host wakapi.local.${SECRET_DOMAIN}

    service:
      main:
        primary: true
        ports:
          http:
            port: 3000

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "speedometer"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "wakatime-tls"
    persistence:
      config:
        enabled: true
        existingClaim: wakapi-pvc
