apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: development
stringData:
    username: ENC[AES256_GCM,data:O+hoAi2LHyY=,iv:1Hfk6eJQ2sU0RFGCHHolCHRiE0z7cRPYr5Zg/tIGaP0=,tag:uCcY3WoZbOhx5tkTA1E7pA==,type:str]
    password: ENC[AES256_GCM,data:CvGZ0rU3R3cBEnkY5FnO,iv:nBpeX51s30TSwoiIjLBs8kLpMd3V1YuUjAUHlM1UGgI=,tag:ws5fkdhoTfQoyZ7tOgrPCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16va2cdyvkrnx6ja24gkf95tgyx003van3ep4030u2z77ekjnpcmsqcn529
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycjBTZE1OdnBnZGFTUFdK
            TWZrbDN1UmJqUTFJN0Y4Y3ZxNXh5ZDNMaGlrCnRTdHhjVk52VWJTTjVCYWdkQ3pv
            MzR6OTBnWXgraDA0azZkSWZuYzBZZHcKLS0tIDBpZ2J0UTRONDhSRGw1a2N2SVc4
            NHEzbVVqL3hoUERRS2JUanZqeU1HUW8Krd7wcRSeAoecE8J5gJ7t4iayoPlYKe07
            CBSga0awLEBsCb3wS7hpB2sn+WZE8R7hEbeGpdZRDy8mpxAAdHF3Xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-22T17:04:02Z"
    mac: ENC[AES256_GCM,data:o8J30jjMnHuPcXZxLuCKqg58bLn2Pc1KmpWCMCeJFQ+3gGIehyjzc4LlURsBkjGtarcKBNJJuSQCD+/L/+IewhEcHmYvrOC6A95HSSnPO3VdSr0ZQsi+HOx1yPUh/1qQNhcNyIsiNE4nd/9zEr/O1mnYipoikmfIDy6EYii+RM0=,iv:2GFS8i9fp5Kw23dKC6+U9puQHQWULYIhdDdT5UTSBok=,tag:m7cT3qpH8uLb+P3JtD0ezQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: wakapi-user
    namespace: development
stringData:
    username: ENC[AES256_GCM,data:91ioxTyP,iv:nEJqO/34gjqS72rxn/v7j1YXRUrZFUc4eUzdSBATiVg=,tag:Idf8g8ukfejygNpsT9gA0w==,type:str]
    password: ENC[AES256_GCM,data:rayCGDPU/O6OtpH4Xa6Lmg==,iv:CKL5tyMM0hPlowPaqjCM+iY2QFiNkyX5DZJpdse7jsA=,tag:l+M3wBP0zES1/Kmjz1ElEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16va2cdyvkrnx6ja24gkf95tgyx003van3ep4030u2z77ekjnpcmsqcn529
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycjBTZE1OdnBnZGFTUFdK
            TWZrbDN1UmJqUTFJN0Y4Y3ZxNXh5ZDNMaGlrCnRTdHhjVk52VWJTTjVCYWdkQ3pv
            MzR6OTBnWXgraDA0azZkSWZuYzBZZHcKLS0tIDBpZ2J0UTRONDhSRGw1a2N2SVc4
            NHEzbVVqL3hoUERRS2JUanZqeU1HUW8Krd7wcRSeAoecE8J5gJ7t4iayoPlYKe07
            CBSga0awLEBsCb3wS7hpB2sn+WZE8R7hEbeGpdZRDy8mpxAAdHF3Xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-22T17:04:02Z"
    mac: ENC[AES256_GCM,data:o8J30jjMnHuPcXZxLuCKqg58bLn2Pc1KmpWCMCeJFQ+3gGIehyjzc4LlURsBkjGtarcKBNJJuSQCD+/L/+IewhEcHmYvrOC6A95HSSnPO3VdSr0ZQsi+HOx1yPUh/1qQNhcNyIsiNE4nd/9zEr/O1mnYipoikmfIDy6EYii+RM0=,iv:2GFS8i9fp5Kw23dKC6+U9puQHQWULYIhdDdT5UTSBok=,tag:m7cT3qpH8uLb+P3JtD0ezQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
