---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wakapi-pvc
  namespace: development
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
