---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-general
  namespace: database
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised

  postgresql:
    pg_hba:
      - host all all all md5

  bootstrap:
    initdb:
      database: general
      owner: eslack
      secret:
        name: postgres-appuser

  storage:
    size: 5Gi
    storageClass: longhorn
  superuserSecret:
    name: postgres-superuser
  monitoring:
    enablePodMonitor: true
