---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-test
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 5Gi
    storageClass: longhorn
  monitoring:
    enablePodMonitor: true
