---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - helm-release.yaml
  - secret.sops.yaml
  - cluster.yaml
  - service.yaml
configMapGenerator:
  - name: cnpg-grafana-dashboards
    files:
      - dashboard/cnpg-dashboard.json
    options:
      labels:
        grafana_dashboard: "1"
