---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: dev
data:
  "5432": "default/postgres-general-rw:5432"
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: dev
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
