{
 "title": "Radarr / Sonarr / Lidarr",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Sonarr Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sonarr_system_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Episodes Missing",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_episode_missing_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Radarr Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "radarr_system_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Movies Missing",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "radarr_movie_missing_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Lidarr Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "radarr_system_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Songs Missing",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lidarr_songs_missing_total", "legendFormat": "__auto" }
   ]
  },
  { "title": "Sonarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "lidarr_system_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total file size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sonarr_series_filesize_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Free space",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sonarr_rootfolder_freespace_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Episodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_episode_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Episodes Missing",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_episode_missing_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Episodes DL Past Month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(sonarr_episode_downloaded_total[30d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Episodes DL Past Week",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(sonarr_episode_downloaded_total[7d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Seasons",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_season_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Seasons Monitored",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_season_monitored_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Seasons DL Past Month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(sonarr_season_downloaded_total[30d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Seasons DL Past Week",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(sonarr_season_downloaded_total[7d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Series",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_series_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Series Monitored",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_series_monitored_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Series DL Past Month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(sonarr_series_downloaded_total[30d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Series DL Past Week",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(sonarr_series_downloaded_total[7d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Radarr",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "radarr_system_status", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Total file size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "radarr_movie_filesize_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Free space",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "radarr_rootfolder_freespace_bytes",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Movies Missing",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "radarr_movie_missing_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Movies Wanted",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "radarr_movie_wanted_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "DL Past Month",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(radarr_movie_download_total[30d]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DL Past Week",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(radarr_movie_download_total[7d]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Movies",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "radarr_movie_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Movies Monitored",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "radarr_movie_monitored_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Movies by quality",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum(radarr_movie_quality_total) by (quality))",
       "legendFormat": "{{quality}}"
      }
     ]
    }
   ]
  },
  { "title": "Lidarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "radarr_system_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total file size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "lidarr_artists_filesize_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Free space",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lidarr_rootfolder_freespace_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Songs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lidarr_songs_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Songs Missing",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lidarr_songs_missing_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Songs DL Past Month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(lidarr_songs_downloaded_total[30d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Songs DL Past Week",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(lidarr_songs_downloaded_total[7d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Albums",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lidarr_albums_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Queued",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lidarr_queue_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Artists",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lidarr_artists_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Artists Monitored",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lidarr_artists_monitored_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Artists by genre",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(lidarr_artists_genres_total) by (genre))",
     "legendFormat": "{{quality}}"
    }
   ]
  }
 ]
}