{
 "title": "Proxmox Monitor",
 "description": "Proxmox Virtual Environment Dashboard",
 "tags": [
  "Proxmox",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(pve_node_info, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Host uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pve_uptime_seconds{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Guests CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((pve_cpu_usage_ratio{job=\"$job\"} / pve_cpu_usage_limit) * on(id, job) group_left(name, type) pve_guest_info) and on(id, job) pve_up == 1",
     "legendFormat": "{{name}} "
    }
   ]
  },
  {
   "title": "Host CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio{job=\"$job\", id=~\"node/.*\"}"
    }
   ]
  },
  {
   "title": "Guests memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(pve_memory_usage_bytes{job=\"$job\"} / pve_memory_size_bytes * on(id, job) group_left(name, type) pve_guest_info) and on(id, job) pve_up == 1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Host Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_memory_usage_bytes{job=\"$job\", id!=\"node/.*\"}  / pve_memory_size_bytes and on(id) pve_node_info"
    }
   ]
  },
  {
   "title": "Resource allocation summary",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (id, name, type) (pve_guest_info{job=\"$job\",template!=\"1\"})"
    },
    {
     "expr": "sum by (id) (pve_up{job=\"$job\",template!=\"1\"} and on (id, job) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_cpu_usage_limit{job=\"$job\",template!=\"1\"} and on (id, job) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_memory_size_bytes{job=\"$job\",template!=\"1\"} and on (id, job) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_memory_usage_bytes{job=\"$job\",template!=\"1\"} / pve_memory_size_bytes and on (id, job) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_disk_size_bytes{job=\"$job\",template!=\"1\"} and on (id, job) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_disk_usage_bytes{job=\"$job\",template!=\"1\"} / pve_disk_size_bytes and on (id, job) pve_guest_info)"
    }
   ]
  },
  {
   "title": "Storage allocation",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_disk_size_bytes{job=\"$job\", id=~\"storage/.+\"} * on (id, job) group_left(storage) pve_storage_info",
     "legendFormat": "{{storage}}"
    }
   ]
  },
  {
   "title": "Guests Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{job=\"$job\"} / pve_disk_size_bytes{job=\"$job\"} * on (id, job) group_left(name, type) pve_guest_info",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{job=\"$job\", id=~\"storage/.+\"} / pve_disk_size_bytes * on (id, job) group_left(storage) pve_storage_info",
     "legendFormat": "{{storage}}"
    }
   ]
  },
  {
   "title": "Network IO/s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(rate(pve_network_receive_bytes{job=\"$job\"}[5m]) * on(id, job) group_left(name, type) pve_guest_info) and on(id, job) pve_up == 1",
     "legendFormat": "{{name}} RECV"
    },
    {
     "expr": "(rate(pve_network_transmit_bytes{instance=\"$instance\"}[5m])* on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} SEND"
    }
   ]
  },
  {
   "title": "Disk IO/s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "((rate(pve_disk_write_bytes{job=\"$job\"}[5m]) + rate(pve_disk_read_bytes[5m])) * on(id, job) group_left(name, type) pve_guest_info) and on(id, job) pve_up == 1",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}