---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mosquitto-exporter-monitor
  namespace: home-automation
  labels:
    app: mosquitto-exporter
spec:
  selector:
    matchLabels:
      app: mosquitto-exporter
  endpoints:
    - port: metrics
      path: '/metrics'
      interval: 30s
