---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensata-exporter-deployment
  labels:
    app: sensata-exporter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sensata-exporter
  template:
    metadata:
      labels:
        app: sensata-exporter
    spec:
      containers:
        - name: sensata-exporter
          image: evanofslack/3vw-logger:latest
          ports:
            - name: http
              containerPort: 5000
            - name: metrics
              containerPort: 8000
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 400m
              memory: 512Mi
          env:
            - name: MQTT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mqtt-creds
                  key: MQTT_USERNAME
                  optional: false
            - name: MQTT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mqtt-creds
                  key: MQTT_PASSWORD
                  optional: false
            - name: MQTT_HOST
              value: ${METALLB_EMQX_ADDR}
            - name: MQTT_PORT
              value: "1883"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
      restartPolicy: Always
