---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - ./deployment.yaml
  - ./service.yaml
commonLabels:
  app.kubernetes.io/name: sensata-exporter
  app.kubernetes.io/instance: sensata-exporter
