---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: network
spec:
  interval: 5m
  timeout: 10m0s
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  values:
    controller:
      replicaCount: 2
      allowSnippetAnnotations: true
      config:
        addHeaders: "network/nginx-custom"
        # taken from https://github.com/ai-robots-txt/ai.robots.txt
        block-user-agents: "~*AdsBot-Google.*,~*Amazonbot.*,~*anthropic-ai.*,~*Applebot-Extended.*,~*Bytespider.*,~*CCBot.*,~*ChatGPT-User.*,~*ClaudeBot.*,~*Claude-Web.*,~*cohere-ai.*,~*Diffbot.*,~*FacebookBot.*,~*FriendlyCrawler.*,~*Google-Extended.*,~*GoogleOther.*,~*GPTBot.*,~*img2dataset.*,~*omgili.*,~*omgilibot.*,~*peer39_crawler.*,~*peer39_crawler/1.0.*,~*PerplexityBot.*,~*YouBot.*"
        client-body-buffer-size: 100M
        client-body-timeout: 120
        client-header-timeout: 120
        custom-http-errors: 400,401,403,404,500,502,503,504
        enable-real-ip: true
        enable-brotli: "true"
        hide-headers: Server,X-Powered-By
        hsts-max-age: 31449600
        log-format-escape-json: "true"
        log-format-upstream:
          '{"time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr", "x_forwarded_for": "$proxy_add_x_forwarded_for", "request_id": "$req_id",
          "remote_user": "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time, "status": $status, "vhost": "$host", "request_proto": "$server_protocol",
          "path": "$uri", "request_query": "$args", "request_length": $request_length, "duration": $request_time,"method": "$request_method", "http_referrer": "$http_referer",
          "http_user_agent": "$http_user_agent" }'
        proxy-body-size: 0
        proxy-buffer-size: 16k
        ssl-prefer-server-ciphers: false
        ssl-protocols: "TLSv1.3 TLSv1.2"
        ssl-redirect: false
        server-tokens: false
        use-forwarded-headers: "true"
      service:
        enabled: true
        type: LoadBalancer
      publishService:
        enabled: true
      metrics:
        enabled: false
      extraArgs:
        default-ssl-certificate: "cert-manager/acme-crt-secret-prod"
      resources:
        requests:
          memory: 500Mi
          cpu: 25m
        limits:
          memory: 800Mi
    defaultBackend:
      enabled: true
      image:
        repository: ghcr.io/tarampampam/error-pages
        tag: 3.3.2
      extraEnvs:
        - name: TEMPLATE_NAME
          value: connection
        - name: SHOW_DETAILS
          value: 'true'
      resources:
        requests:
          memory: 250Mi
          cpu: 25m
        limits:
          memory: 350Mi
