apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: security
stringData:
    username: ENC[AES256_GCM,data:AQbV//c6L5s=,iv:MglGUWBTh+uw04id3JyanuvcjHZhK5dcad5GCJP7gDo=,tag:g5iV6O6mBruh5s92qhtZ3w==,type:str]
    password: ENC[AES256_GCM,data:AlzO4z+iyBBpMY+K6rKp,iv:uojlhNC5XKe+va/Ik8GvcZdL8RgvpJaiX1a0oxef4gY=,tag:DBejwWpliA1c4IEb/UlM6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16va2cdyvkrnx6ja24gkf95tgyx003van3ep4030u2z77ekjnpcmsqcn529
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWG5TMks5YmpHV211Nzhy
            MXU5OXRrNVZNelNTL0VlV3hPZGFpUEo0eVFzCkk5OFVnRWRKZlNIeUViQkRjbVlv
            Z1VCV0VZZkQxYnMzVm1KbWk0d3lmRWsKLS0tIExCMGtwRThKNTJRaGsreHRBNnNI
            K2dVekpQdGowL0hzNXRKYXdDWGNYalUKFGxcF5erZrDEgvDC0bxleQ+iomLp/mUl
            QP5opEeI3ff7scMei8ObWvKJXIE5OwSwMnSvCwxAJ93zaPsFCDM23w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-26T04:18:07Z"
    mac: ENC[AES256_GCM,data:7ftAUx3/MrYogx68urF0kLRZYcb2NePZ2nq5aZZ9LloaLiMSnW07JGs3+T/QGGkJoyJB6hAmlmyid8ATGv3tBDl7+ZDBeGn8AtQaGFFFOjmwdtCkxp0khqvRHAFruAUo2kn5qv0GdO0TD+QP4TzFDcHEKJmFIQHYHtDcoYny4UU=,iv:AVwejYrQGLgcY5uX36qBGL4nq+OAZRUv/IL41fl6IBE=,tag:DQzYTgW23/0pC0t6lYNvlA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: vaultwarden-user
    namespace: security
stringData:
    username: ENC[AES256_GCM,data:DBnHNZp9MvkFc+c=,iv:kOBvZEh8Ni1+YrvTdmlfboB91MMwZdB2wa4POHlsjVg=,tag:hI5pjeBG8yYKarmaeHubMA==,type:str]
    password: ENC[AES256_GCM,data:nMlT21CT91/7OOhf1Ls=,iv:6sgnhvwFrSCDF7lEWUdZk3FByAu9EhyawT5TZzpvZnI=,tag:7r9JaPrawQ7wDMYrsfR2WA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16va2cdyvkrnx6ja24gkf95tgyx003van3ep4030u2z77ekjnpcmsqcn529
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWG5TMks5YmpHV211Nzhy
            MXU5OXRrNVZNelNTL0VlV3hPZGFpUEo0eVFzCkk5OFVnRWRKZlNIeUViQkRjbVlv
            Z1VCV0VZZkQxYnMzVm1KbWk0d3lmRWsKLS0tIExCMGtwRThKNTJRaGsreHRBNnNI
            K2dVekpQdGowL0hzNXRKYXdDWGNYalUKFGxcF5erZrDEgvDC0bxleQ+iomLp/mUl
            QP5opEeI3ff7scMei8ObWvKJXIE5OwSwMnSvCwxAJ93zaPsFCDM23w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-26T04:18:07Z"
    mac: ENC[AES256_GCM,data:7ftAUx3/MrYogx68urF0kLRZYcb2NePZ2nq5aZZ9LloaLiMSnW07JGs3+T/QGGkJoyJB6hAmlmyid8ATGv3tBDl7+ZDBeGn8AtQaGFFFOjmwdtCkxp0khqvRHAFruAUo2kn5qv0GdO0TD+QP4TzFDcHEKJmFIQHYHtDcoYny4UU=,iv:AVwejYrQGLgcY5uX36qBGL4nq+OAZRUv/IL41fl6IBE=,tag:DQzYTgW23/0pC0t6lYNvlA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: vaultwarden-postgres
    namespace: security
stringData:
    POSTGRES_URL: ENC[AES256_GCM,data:M/iHuMvbccva/MBLyUv4m4JoXhftPiO1QH+G3W7626MXL9u8gJVN26kAAU+dnwonKTNFWeibkYtZb6nxvhNsDb43HzUZdEXfqiot/l+OoWE4Gtol9RmHQyo1NZda,iv:BBB+X37eNFEwpnK3Ql5eayQcioxrfF+w2AcvuOeYBxg=,tag:cVFSQg09vvo7Q1zuCVC+Ow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16va2cdyvkrnx6ja24gkf95tgyx003van3ep4030u2z77ekjnpcmsqcn529
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWG5TMks5YmpHV211Nzhy
            MXU5OXRrNVZNelNTL0VlV3hPZGFpUEo0eVFzCkk5OFVnRWRKZlNIeUViQkRjbVlv
            Z1VCV0VZZkQxYnMzVm1KbWk0d3lmRWsKLS0tIExCMGtwRThKNTJRaGsreHRBNnNI
            K2dVekpQdGowL0hzNXRKYXdDWGNYalUKFGxcF5erZrDEgvDC0bxleQ+iomLp/mUl
            QP5opEeI3ff7scMei8ObWvKJXIE5OwSwMnSvCwxAJ93zaPsFCDM23w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-26T04:18:07Z"
    mac: ENC[AES256_GCM,data:7ftAUx3/MrYogx68urF0kLRZYcb2NePZ2nq5aZZ9LloaLiMSnW07JGs3+T/QGGkJoyJB6hAmlmyid8ATGv3tBDl7+ZDBeGn8AtQaGFFFOjmwdtCkxp0khqvRHAFruAUo2kn5qv0GdO0TD+QP4TzFDcHEKJmFIQHYHtDcoYny4UU=,iv:AVwejYrQGLgcY5uX36qBGL4nq+OAZRUv/IL41fl6IBE=,tag:DQzYTgW23/0pC0t6lYNvlA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
