version: "3.8"

services:
  k6:
    image: grafana/k6
    ports:
      - 6565:6565
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=${K6_PROMETHEUS_RW_SERVER_URL}
      - K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM=${K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM}
    volumes:
      - ./scripts:/scripts

networks:
  default:
    external: true
    name: mon

