{
 "title": "3VW Monitor",
 "tags": [ "Sensata" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Topics",
    "query": {
     "query": "label_values(sensata_subscribed_topics, topic)"
    }
   },
   {
    "name": "DUT",
    "label": "DUT",
    "query": {
     "query": "label_values(sensata_msg_total, DUT)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "<div align=\"center\">\r\n<img src=\"http://cdn.shopify.com/s/files/1/0627/9839/7681/files/logo_sensta-iq-vertical-image_41fad715-c66a-4649-ba0c-832f02cde07c.png?v=1648722158\" />\r\n</div>"
   }
  },
  {
   "title": "Temperature - $DUT ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (instance, pod) (sensata_temperature{DUT=~\"$DUT\"})",
     "legendFormat": "{{DUT}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "3VW Temperature (TMP117)",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg without (instance, pod) (sensata_temperature)",
     "legendFormat": "{{DUT}}"
    }
   ]
  },
  {
   "title": "Sensors Online",
   "type": "stat",
   "description": "Total number of unique 3VW devices registered to broker",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Sensors" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (instance, pod) (sensata_DUT_total)"
    }
   ]
  },
  { "title": "Broker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Broker Instances",
   "type": "stat",
   "description": "Number of MQTT instances running",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (namespace) (emqx_cluster_nodes_running)",
     "legendFormat": "{{sensata_broker_status}}"
    }
   ]
  },
  {
   "title": "Monitor Uptime",
   "type": "stat",
   "description": "Cumulative time 3VW logger has been running",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without (instance, pod) (time() - sensata_broker_start{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Messages by DUT",
   "type": "timeseries",
   "description": "Total number of messages received by broker",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by(DUT) (sensata_msg_total{modality=\"all\"})",
     "legendFormat": "{{DUT}}"
    }
   ]
  },
  {
   "title": "Total Messages by Modality",
   "type": "timeseries",
   "description": "Total number of messages received by broker",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by(modality) (sensata_msg_total{modality!=\"all\"})",
     "legendFormat": "{{DUT}}"
    }
   ]
  },
  {
   "title": "Total Messages Received",
   "type": "stat",
   "description": "Total number of unique messages received by broker",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (instance, pod, service, job) (emqx_messages_received)"
    }
   ]
  },
  {
   "title": "Message Rate",
   "type": "gauge",
   "description": "Rate of received messages by broker",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(emqx_messages_received[1h]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Vibration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "accG" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (instance, pod) (sensata_accel_p2p{DUT=~\"$DUT\"})",
     "legendFormat": "{{axis}}"
    }
   ]
  },
  {
   "title": "Vibration P2P",
   "type": "timeseries",
   "description": "Accelerometer peak to peak acceleration (G)",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "accG" } },
   "targets": [
    {
     "expr": "avg without (instance, pod) (sensata_accel_p2p{DUT=~\"$DUT\"})",
     "legendFormat": "{{DUT}}"
    }
   ]
  },
  {
   "title": "Noise",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (instance, pod) (sensata_acoustic_p2p{DUT=~\"$DUT\"} + 2 ^ 5)",
     "legendFormat": "{{DUT}}"
    }
   ]
  },
  {
   "title": "Microphone",
   "type": "timeseries",
   "description": "Acoustic microphone peak to peak (Volts)",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "avg without (instance, pod) (sensata_acoustic_p2p + 2 ^ 5)",
     "legendFormat": "{{DUT}}"
    }
   ]
  },
  { "title": "Modalities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } }
 ]
}