---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: 3vw-logger-monitor
  namespace: monitoring
  labels:
    app: 3vw-logger
    prometheus: monitoring
spec:
  endpoints:
    - port: metrics
      path: '/metrics'
      interval: 30s
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: 3vw-logger
      prometheus: monitoring
