version: "3.7"

services:
  nut-exporter:
    image: hon95/prometheus-nut-exporter:1
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - HTTP_PATH=/metrics
      - RUST_LOG=info
    ports:
      - 9995:9995
