{
 "title": "Workstation",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "{__name__=~\"ohm_.*\"}"
    }
   },
   {
    "name": "hdd",
    "query": {
     "query": "{__name__=~\"ohm_hdd_.*\",instance=\"$instance\"}"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "{__name__=~\"ohm_nic_.*\",instance=\"$instance\"}"
    }
   },
   {
    "name": "cpu",
    "query": {
     "query": "{__name__=~\"ohm_cpu_.*\",instance=\"$instance\"}"
    }
   },
   {
    "name": "gpu",
    "query": {
     "query": "{__name__=~\"ohm_gpu.*\",instance=\"$instance\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Current Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_cpu_load_percent{instance=\"$instance\",sensor=\"CPU Total\"}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_ram_load_percent{instance=\"$instance\",sensor=\"Memory\"}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ohm_hdd_load_percent{instance=\"$instance\",sensor=\"Total Activity\"})"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ohm_hdd_load_percent{instance=\"$instance\",sensor=\"Used Space\"})"
    }
   ]
  },
  {
   "title": "Disk Reads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ohm_hdd_bytes{instance=\"$instance\", sensor=\"Data Read\"}[$__range]))",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Disk Writes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ohm_hdd_bytes{instance=\"$instance\", sensor=\"Data Written\"}[$__range]))",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "table",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "{instance=\"$instance\",__name__=~\"ohm_.*_celsius\", sensor!~\".*Distance to TjMax\"}"
    }
   ]
  },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ohm_nic_bytes{instance=\"$instance\",sensor=\"Data Downloaded\"}[$__range]))",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Uploads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ohm_nic_bytes{instance=\"$instance\",sensor=\"Data Uploaded\"}[$__range]))",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "GPU Compute",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_gpunvidia_load_percent{instance=\"$instance\",sensor=\"GPU Core\"}"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_gpunvidia_bytes{instance=\"$instance\",sensor=\"GPU Memory Used\"} * 100 / ignoring(sensor) ohm_gpunvidia_bytes{instance=\"$instance\",sensor=\"GPU Memory Total\"}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ohm_nic_load_percent{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Fan",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max({__name__=~\"ohm_.*_control_percent\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Disk Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ohm_hdd_bytes_per_second{instance=\"$instance\"})",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Network Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ohm_nic_bytes_per_second{instance=\"$instance\"})",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  { "title": "CPU: $cpu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }, "repeat": "cpu" },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ohm_cpu_load_percent{instance=\"$instance\",sensor!=\"CPU Total\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Wattage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "repeat": "power",
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ohm_cpu_watts{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "repeat": "hardtemp",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ohm_cpu_celsius{instance=\"$instance\",sensor!~\".*Distance to TjMax\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Volts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "repeat": "volts",
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "ohm_cpu_volts{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Frequencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "repeat": "cpu",
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "ohm_cpu_hertz{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  { "title": "GPU: $gpu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 }, "repeat": "gpu" },
  {
   "title": "GPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ohm_gpunvidia_load_percent{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    },
    {
     "expr": "ohm_gpuati_load_percent{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Wattage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "repeat": "power",
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ohm_gpunvidia_watts{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    },
    {
     "expr": "ohm_gpuati_watts{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "repeat": "hardtemp",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ohm_gpunvidia_celsius{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    },
    {
     "expr": "ohm_gpuati_celsius{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "ohm_gpunvidia_bytes_per_second{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ohm_gpunvidia_bytes{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Fan",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "ohm_gpunvidia_revolutions_per_minute{instance=\"$instance\"}",
     "legendFormat": "Fan"
    },
    {
     "expr": "(max(ohm_gpunvidia_revolutions_per_minute{instance=\"$instance\"}) / ignoring(sensor) (max(ohm_gpunvidia_control_percent{instance=\"$instance\"}) / 100)) * 0.9",
     "legendFormat": "High RPM"
    }
   ]
  },
  {
   "title": "Frequencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "repeat": "cpu",
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "ohm_gpunvidia_hertz{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    },
    {
     "expr": "ohm_gpuati_hertz{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  { "title": "Drives", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Drives",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "max by (hardware,hw_instance) (ohm_hdd_celsius{instance=\"$instance\"})"
    },
    {
     "expr": "ohm_hdd_bytes{instance=\"$instance\",sensor=\"Data Read\"}"
    },
    {
     "expr": "ohm_hdd_bytes{instance=\"$instance\",sensor=\"Data Written\"}"
    },
    {
     "expr": "sum by (hardware,hw_instance) (increase(ohm_hdd_bytes{instance=\"$instance\",sensor=\"Data Read\"}[$__range]))"
    },
    {
     "expr": "sum by (hardware,hw_instance) (increase(ohm_hdd_bytes{instance=\"$instance\",sensor=\"Data Written\"}[$__range]))"
    },
    {
     "expr": "ohm_hdd_load_percent{instance=\"$instance\",sensor=\"Used Space\"}"
    },
    {
     "expr": "ohm_hdd_factor{instance=\"$instance\",sensor=\"Power Cycles\"}"
    },
    {
     "expr": "ohm_hdd_factor{instance=\"$instance\",sensor=\"Media Errors\"}"
    }
   ]
  },
  { "title": "Drive: $hdd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 }, "repeat": "hdd" },
  {
   "title": "$hdd Factors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ohm_hdd_factor{instance=\"$instance\",hw_instance=\"$hdd\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ohm_hdd_celsius{instance=\"$instance\",hw_instance=\"$hdd\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Disk Activity Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ohm_hdd_load_percent{instance=\"$instance\",hw_instance=\"$hdd\",sensor=\"Total Activity\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "ohm_hdd_load_percent{instance=\"$instance\",hw_instance=\"$hdd\",sensor=\"Write Activity\"}",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Disk Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "ohm_hdd_bytes_per_second{instance=\"$instance\",hw_instance=\"$hdd\",sensor=\"Read Rate\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "-ohm_hdd_bytes_per_second{instance=\"$instance\",hw_instance=\"$hdd\",sensor=\"Write Rate\"}",
     "legendFormat": "Write"
    }
   ]
  },
  { "title": "Motherboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ohm_superio_celsius{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Fan",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "ohm_superio_revolutions_per_minute{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    },
    {
     "expr": "(max(ohm_superio_revolutions_per_minute{instance=\"$instance\"}) / ignoring(sensor) (max(ohm_superio_control_percent{instance=\"$instance\"}) / 100)) * 0.9",
     "legendFormat": "High RPM"
    }
   ]
  },
  {
   "title": "Volts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 105 },
   "repeat": "volts",
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "ohm_superio_volts{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 } },
  {
   "title": "Network Usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "targets": [
    {
     "expr": "sum by (hardware) (increase(ohm_nic_bytes{instance=\"$instance\",sensor=\"Data Downloaded\"}[$__range]))"
    },
    {
     "expr": "sum by (hardware) (increase(ohm_nic_bytes{instance=\"$instance\",sensor=\"Data Uploaded\"}[$__range]))"
    },
    {
     "expr": "ohm_nic_load_percent{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "$network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 124 },
   "repeat": "network",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "ohm_nic_bytes_per_second{instance=\"$instance\",hardware=~\"$network\",sensor=\"Download Speed\"}",
     "legendFormat": "Download"
    },
    {
     "expr": "-ohm_nic_bytes_per_second{instance=\"$instance\",hardware=~\"$network\",sensor=\"Upload Speed\"}",
     "legendFormat": "Upload"
    }
   ]
  }
 ]
}