---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cloudflare-ddns
  - cloudflare-tunnel
  - external-dns
  - ingress-nginx
  - k8s-gateway
  - metallb
  - reverse-proxy
