apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: mqtt-creds
    namespace: home-automation
stringData:
    MQTT_USERNAME: ENC[AES256_GCM,data:Po73lsuc,iv:wEegSRApZqUkPViaPazjg8J6WQ6U/XT6S+eZ1IAzzqM=,tag:vPxFqq0tBn0+2YKHCK1bAw==,type:str]
    MQTT_PASSWORD: ENC[AES256_GCM,data:rR8reCBh1mkL,iv:GyHQRscKMi9T+k5Bnn/Mw19BHwmd1bGQOR7J/Kek4nU=,tag:wbdyFTD+VXpF4IDOx3Lr8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16va2cdyvkrnx6ja24gkf95tgyx003van3ep4030u2z77ekjnpcmsqcn529
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSjdQS2tCTlhCOFA4TUho
            Q2FQK3MwUG1tQ1ErSGZLelFYS3dZMnhzdlJNClFpQWdYTStsU1B5WmQ1U0ZpenFp
            MHk2M1U4dEZ2eFI2YndWOEw0MGYxUTAKLS0tIFZiNTRvQkFwem9rNWlGbVlPN1Nu
            cjZ4QXJ0ekJ5b3RUd0I0ZWY5NklkQTQKjdGD3qnuHFYB+Ph3DfpnDbUj88KSjQAG
            tx2FEgazIjhx8mhvfHLAwr2koiBHf/XBglXOfUgNhaXgrwSa/lE3Gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-29T23:40:49Z"
    mac: ENC[AES256_GCM,data:RAKUpMdChygQc4uG59+D8btIkcyF6NjicyX87TRqLykMM9d9h+eMbqGb/Gl4LfFGC9Lnl7yi/cY2S2F6FL8M95qGkZnPttdfqXWlr6aZ3LUNFwAKOujpRR3Vms4gqTqEAWVNI6v/TtXvPA8nUfdw5VHvecy8NlE76IsWpaDkYk0=,iv:Kmyq59uNmjxdwECHL+88A8WWe7Su3Zq7GCdD3672zuk=,tag:PZ0w8eALliWGOUwlWXMDmA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
