---
kubernetes:
  children:
    master:
      hosts:
        master-0:
          ansible_host: 10.33.1.200
        master-1:
          ansible_host: 10.33.1.201
        master-2:
          ansible_host: 10.33.1.202
    worker:
      hosts:
        worker-0:
          ansible_host: 10.33.1.203
        worker-1:
          ansible_host: 10.33.1.204
        worker-2:
          ansible_host: 10.33.1.205
        store-0:
          ansible_host: 10.33.1.209
        store-1:
          ansible_host: 10.33.1.210
        store-2:
          ansible_host: 10.33.1.211
