---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
configMapGenerator:
  - name: custom-grafana-dashboards
    files:
      - dashboards/proxmox-monitor.json
    options:
      labels:
        grafana_dashboard: "1"
