---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app hakatime
  namespace: development
spec:
  releaseName: *app
  interval: 15m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: cloudnative-pg
      namespace: database
  values:
    global:
      nameOverride: *app
    image:
      repository: mujx/hakatime
      tag: latest
    env:
      HAKA_DB_HOST: postgres-hakatime-rw
      HAKA_DB_PORT: 5432
      HAKA_DB_NAME: "hakatime"
      HAKA_DB_USER: "hakatime"
      HAKA_DB_PASS:
        valueFrom:
          secretKeyRef:
            name: hakatime-user
            key: password
      HAKA_PORT: 8080
      HAKA_ENABLE_REGISTRATION: "true"
      HAKA_SESSION_EXPIRY: "24"
      HAKA_LOG_LEVEL: "info"
      HAKA_ENV: "prod"
      HAKA_HTTP_LOG: "true"
      # GITHUB_TOKEN: "<token>" # If you want to retrieve time spent per commit. No extra scope is required.

    service:
      main:
        enabled: true
        nameOverride: service-hakatime
        primary: true
        ports:
          http:
            port: &port 8080
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "file-code-outline"
          hajimari.io/appName: "Hakatime"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        hosts:
          - host: &host hakatime.local.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: *port
        tls:
          - hosts:
              - *host
            secretName: "hakatime-tls"
    persistence:
      config:
        enabled: true
        existingClaim: hakatime-config
