apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats
  namespace: lab
spec:
  interval: 5m
  chart:
    spec:
      chart: nats
      version: "1.3.6"
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: flux-system
  values:
    config:
      cluster:
        enabled: true
        replicas: 3

      jetstream:
        enabled: true
        
        memoryStore:
          enabled: true
          maxSize: 8Gi
        
        fileStore:
          enabled: true
          pvc:
            enabled: true
            size: 100Gi
            storageClassName: ceph-filesystem
      
      monitor:
        enabled: true

    natsBox:
      enabled: true

    promExporter:
      enabled: true
      podMonitor:
        enabled: true 
    
    podDisruptionBudget:
      enabled: true
