apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats
  namespace: lab
spec:
  interval: 5m
  chart:
    spec:
      chart: nats
      version: "1.3.6"
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: flux-system
  values:
    nats:
      jetstream:
        enabled: true
        memStorage:
          enabled: true
          size: 8Gi
        fileStorage:
          enabled: true
          size: 100Gi
          storageClassName: ceph-filesystem
      
    cluster:
      enabled: true
      replicas: 3  

    natsBox:
      enabled: true

    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true  
