---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-crt-prod
  namespace: cert-manager
spec:
  secretName: acme-crt-secret-prod
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - eslack.net
  - '*.eslack.net'
  - '*.local.eslack.net'

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-crt-stage
  namespace: cert-manager
spec:
  secretName: acme-crt-secret-stage
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - eslack.net
  - '*.eslack.net'
  - '*.local.eslack.net'
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
