---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-secrets
  namespace: network
spec:
  target:
    name: cert-manager-secrets
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashi-vault
  data:
    - secretKey: cloudflare-api-token
      remoteRef:
        key: cloudflare
        property: api_token

