apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: hashi-vault
spec:
  provider:
    vault:
      server: https://vault.local.eslack.net
      path: k8s-secrets
      version: v2
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
