{
 "title": "Weaviate",
 "tags": [ "weaviate" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "class", "query": { "query": "label_values(class_name)" } },
   { "name": "shard", "query": { "query": "label_values(shard_name)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Startup Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "startup_durations_ms_sum{operation=\"shard_total_init\", shard_name=~\"$shard\"}",
     "legendFormat": "Vectors Inserted"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"analogdb-weaviate\"}",
     "legendFormat": "{{class_name}}"
    }
   ]
  },
  {
   "title": "Shards",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(object_count{job=\"analogdb-weaviate\"})",
     "legendFormat": "Vectors Inserted"
    }
   ]
  },
  {
   "title": "Classes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vector_index_size{job=\"analogdb-weaviate\"}) ",
     "legendFormat": "Vectors Inserted"
    }
   ]
  },
  {
   "title": "$class Vector Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vector_index_size{class_name=\"$class\", shard_name=\"$shard\"}",
     "legendFormat": "{{class_name}}"
    }
   ]
  },
  {
   "title": "Total Vector Queries",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "queries_filtered_vector_durations_ms_count{class_name=\"$class\", shard_name=\"$shard\", operation=\"vector\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Total Vectors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vector_index_operations{operation=\"create\", class_name=\"$class\", shard_name=\"$shard\"}) - sum(vector_index_operations{operation=\"delete\", class_name=\"$class\", shard_name=\"$shard\"})",
     "legendFormat": "Vectors Inserted"
    }
   ]
  },
  {
   "title": "Total Objects",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "object_count{class_name=\"$class\", shard_name=\"$shard\"}",
     "legendFormat": "Vectors Inserted"
    }
   ]
  },
  { "title": "Create and Delete", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Vectors Created",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(vector_index_operations{operation=\"create\", class_name=\"$class\", shard_name=\"$shard\"}[$__range])",
     "legendFormat": "Vectors Inserted"
    }
   ]
  },
  {
   "title": "Vector Operation Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(vector_index_operations{class_name=\"$class\", shard_name=\"$shard\"}[$__rate_interval])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Vector Operation Timing",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(vector_index_durations_ms_sum{class_name=\"$class\", shard_name=\"$shard\"}[$__rate_interval])/rate(vector_index_durations_ms_count{class_name=\"$class\", shard_name=\"$shard\"}[$__rate_interval])",
     "legendFormat": "{{operation}} - {{step}}"
    }
   ]
  },
  {
   "title": "Vectors Deleted",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(vector_index_operations{operation=\"delete\", class_name=\"$class\", shard_name=\"$shard\"}[$__range])",
     "legendFormat": "Vectors Inserted"
    }
   ]
  },
  { "title": "Batch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Batch Uploads",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(batch_durations_ms_count{class_name=\"$class\", shard_name=\"$shard\", operation=\"vector_storage\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(batch_durations_ms_sum{class_name=\"$class\", shard_name=\"$shard\"}[$__rate_interval])/rate(batch_durations_ms_count{class_name=\"$class\", shard_name=\"$shard\"}[$__rate_interval])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Batch Duration Q90",
   "type": "histogram",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(batch_durations_ms_bucket{class_name=\"$class\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Batch Uploads",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "concurrent_queries_count{query_type=\"batch\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Batch Objects Latency (Components & Totals)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(batch_durations_ms_sum{}[$__rate_interval])/rate(batch_durations_ms_count{}[$__rate_interval])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Persistence Tasks (Object, Vector)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(batch_durations_ms_sum{operation=\"object_storage\"}[$__rate_interval])/rate(batch_durations_ms_count{operation=\"object_storage\"}[$__rate_interval])",
     "legendFormat": "Object Storage ({{class_name}} - {{shard_name}})"
    },
    {
     "expr": "rate(batch_durations_ms_sum{operation=\"vector_storage\"}[$__rate_interval])/rate(batch_durations_ms_count{operation=\"vector_storage\"}[$__rate_interval])",
     "legendFormat": "Vector Storage ({{class_name}} - {{shard_name}})"
    }
   ]
  },
  {
   "title": "Reassigned Nodes",
   "type": "stat",
   "description": "If a node had an outgoing connection to another node that received a tombstone it must be reassigned.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vector_index_tombstone_cleaned)"
    }
   ]
  },
  {
   "title": "Active Tombstone Cleanup Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 44 },
   "targets": [
    {
     "expr": "vector_index_tombstone_cleanup_threads",
     "legendFormat": "{{class_name}} - {{shard_name}}"
    }
   ]
  },
  {
   "title": "HNSW Tombstones",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(vector_index_tombstones)" }
   ]
  },
  {
   "title": "Active Tombstones in HNSW index",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 53 },
   "targets": [
    {
     "expr": "vector_index_tombstones",
     "legendFormat": "{{class_name}} - {{shard_name}}"
    }
   ]
  },
  {
   "title": "Tombstone Cleanup Threads",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vector_index_tombstone_cleanup_threads)"
    }
   ]
  },
  {
   "title": "Heap in use (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"analogdb-weaviate\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Active LSM Segments (summed by type)",
   "type": "timeseries",
   "description": "Count of active segments across all classes and shards, shown by type.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "expr": "sum(lsm_active_segments{strategy=\"replace\"})",
     "legendFormat": "Total \"Replace\" (Object Storage)"
    },
    {
     "expr": "sum(lsm_active_segments{strategy=\"mapcollection\"})",
     "legendFormat": "Total \"Map\" (Inverted storage with term frequency)"
    },
    {
     "expr": "sum(lsm_active_segments{strategy=\"setcollection\"})",
     "legendFormat": "Total \"Set\" (Inverted storage without frequency)"
    }
   ]
  }
 ]
}