---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app external-secrets
  namespace: flux-system
spec:
  targetNamespace: secrets
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  wait: true
  interval: 30m
  path: ./clusters/cluster/apps/secrets/external-secrets/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app external-secrets-stores
  namespace: flux-system
spec:
  targetNamespace: secrets
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets
  path: ./clusters/cluster/apps/secrets/external-secrets/stores
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  timeout: 5m
