---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb-kubernetes-operator
  namespace: database
spec:
  interval: 15m
  chart:
    spec:
      chart: community-operator
      version: 0.7.5
      sourceRef:
        kind: HelmRepository
        name: mongodb
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    operator:
      name: mongodb-kubernetes-operator
      operatorImageName: mongodb-kubernetes-operator
      deploymentName: mongodb-kubernetes-operator
      version: 0.7.5
      watchNamespace: "*"
      resources:
        limits:
          cpu: 1000m
          memory: 500Mi
        requests:
          cpu: 300m
          memory: 150Mi
    database:
      name: mongodb-database
      namespace: database
    registry:
      pullPolicy: IfNotPresent
    community-operator-crds:
      enabled: true
