---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb-kubernetes-operator
  namespace: database
spec:
  interval: 15m
  chart:
    spec:
      chart: community-operator
      version: 0.7.5
      sourceRef:
        kind: HelmRepository
        name: mongodb
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    operator:
      name: mongodb-kubernetes-operator
      operatorImageName: mongodb-kubernetes-operator
      deploymentName: mongodb-kubernetes-operator
      version: 0.7.5
      watchNamespace: "*"
      resources:
        limits:
          cpu: 1000m
          memory: 500mi
        requests:
          cpu: 300m
          memory: 150Mi
    database: # Operator's database
      name: mongodb-database
      namespace: database
    agent:
      name: mongodb-agent
      version: 11.12.0.7388-1
    versionUpgradeHook:
      name: mongodb-kubernetes-operator-version-upgrade-post-start-hook
      version: 1.0.5
    readinessProbe:
      name: mongodb-kubernetes-readinessprobe
      version: 1.0.11
    mongodb:
      name: mongo
      repo: docker.io
    registry:
      agent: quay.io/mongodb
      versionUpgradeHook: quay.io/mongodb
      readinessProbe: quay.io/mongodb
      operator: quay.io/mongodb
      pullPolicy: IfNotPresent
    community-operator-crds:
      enabled: true
    createResource: false
    resource:
      name: mongodb-replica-set
      version: 4.4.0
      members: 3
      tls:
        enabled: false
