---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - helm-release.yaml
  - secret.sops.yaml
  - service-monitor.yaml
configMapGenerator:
  - name: mongodb-grafana-dashboards
    files:
      - dashboard/mongodb-dashboard.json
    options:
      labels:
        grafana_dashboard: "1"
