apiVersion: v1
kind: Secret
metadata:
    name: my-user-password
    namespace: mongodb
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:5cg3yGbqSxZ0rtbWrlA=,iv:7Zog7OFxNOgloLsiRw+whL8tdeSI72URqct8sTJ2FjU=,tag:BNTzX6/0oRbP/U65s+uDSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16va2cdyvkrnx6ja24gkf95tgyx003van3ep4030u2z77ekjnpcmsqcn529
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bUdYaGhNNlVrVjF4aGt5
            TGwreW1EZlgzRSt6VDZ4bVdvYWNaYVE0OGdrCkZCTG1YcDQwZi9jMkF2dUtRaGlE
            YlJGTnVoV2lwU003cXdTajVOcTlmMzgKLS0tIEw5YUVXV3hBL0Y1Tm9IV1NjUzN5
            Y2NrWS9iTDhqUGZ4MmFJN3ZVcjgrSncK/9382P67MvRSlLU6ZoOK/RYVPL/sL1YT
            VZ/3jNsJMHzP8mcbcWm1wYf3XozuMSR+kheGMS6LWC6agHs12KMMlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-24T00:12:56Z"
    mac: ENC[AES256_GCM,data:IXh1gGGeHXpjv8IpFw22nwqzsxgPaaTcumAWLUWi7FkOaBrEmKAojZl7stMZCXkWpI9wV/XYpwiHj/qfcyYzIXcwxQgwNydNSnysM9r1UBmXkTsKAXHzjVWzmX2Z0TFkCUWF60wJGcQSf2mgdo08Lptd4SV6XIDlrYFlDpNOGhA=,iv:FDMHgQw6ouwzi7Er6zObGS1Vsw1yWdMiubraVg67j0k=,tag:STVfRR+INovFQPzHejI46w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: metrics-endpoint-password
    namespace: mongodb
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:gojXGdOOVm3PFxmYGAA=,iv:v882HC7gXk8h/PSB1VFz9aH5QAmkxz2nb24k0zvrR50=,tag:u1WMt4+dmUEkxHKBbfdclw==,type:str]
    username: ENC[AES256_GCM,data:/VWsU1ejR3d6Qc9GwzoUkFgEKw==,iv:jjym8IHLKUjI8ZaYAe/Ya8WF3fYCRV7NBpFXonaw0Y8=,tag:WqTti4TjxKaC0+jpxjqmzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16va2cdyvkrnx6ja24gkf95tgyx003van3ep4030u2z77ekjnpcmsqcn529
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bUdYaGhNNlVrVjF4aGt5
            TGwreW1EZlgzRSt6VDZ4bVdvYWNaYVE0OGdrCkZCTG1YcDQwZi9jMkF2dUtRaGlE
            YlJGTnVoV2lwU003cXdTajVOcTlmMzgKLS0tIEw5YUVXV3hBL0Y1Tm9IV1NjUzN5
            Y2NrWS9iTDhqUGZ4MmFJN3ZVcjgrSncK/9382P67MvRSlLU6ZoOK/RYVPL/sL1YT
            VZ/3jNsJMHzP8mcbcWm1wYf3XozuMSR+kheGMS6LWC6agHs12KMMlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-24T00:12:56Z"
    mac: ENC[AES256_GCM,data:IXh1gGGeHXpjv8IpFw22nwqzsxgPaaTcumAWLUWi7FkOaBrEmKAojZl7stMZCXkWpI9wV/XYpwiHj/qfcyYzIXcwxQgwNydNSnysM9r1UBmXkTsKAXHzjVWzmX2Z0TFkCUWF60wJGcQSf2mgdo08Lptd4SV6XIDlrYFlDpNOGhA=,iv:FDMHgQw6ouwzi7Er6zObGS1Vsw1yWdMiubraVg67j0k=,tag:STVfRR+INovFQPzHejI46w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
