---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
  namespace: database
spec:
  members: 3
  type: ReplicaSet
  version: "5.0.6"

  prometheus:
    username: prometheus-username
    passwordSecretRef:
      name: metrics-endpoint-password

  security:
    authentication:
      modes: ["SCRAM"]

  users:
    - name: my-user
      db: admin
      passwordSecretRef:
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
