{
 "title": "Caddy",
 "tags": [ "caddy" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "handler",
    "label": "handler",
    "query": {
     "query": "label_values(caddy_admin_http_requests_total,handler)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(up{job=~\"caddy.*\"},instance)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_request_duration_seconds_count[$__range]))"
    }
   ]
  },
  {
   "title": "Error Percent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_request_errors_total[$__range])) / sum(increase(caddy_http_request_duration_seconds_count[$__range]))"
    }
   ]
  },
  {
   "title": "Bytes In",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_request_size_bytes_sum[$__range]))"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_response_size_bytes_sum[$__range]))"
    }
   ]
  },
  {
   "title": "Reverse Proxy Entries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(caddy_reverse_proxy_upstreams_healthy)"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Rate (Method)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(method) (rate(caddy_http_request_duration_seconds_count{instance=~\"$host\"}[2m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Rate (Response Code)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(code) (rate(caddy_http_request_duration_seconds_count{instance=~\"$host\"}[2m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  { "title": "Durations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Request Duration (Heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_request_duration_seconds_bucket[2m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Duration (Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(caddy_http_request_duration_seconds_bucket[2m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(caddy_http_request_duration_seconds_bucket[2m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(caddy_http_request_duration_seconds_bucket[2m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  { "title": "Bytes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Byte Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(caddy_http_response_size_bytes_sum{instance=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "response"
    },
    {
     "expr": "sum(rate(caddy_http_request_size_bytes_sum{instance=~\"$host\"}[2m])) * -1",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Median Response Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(caddy_http_response_size_bytes_bucket{instance=~\"$host\"}[2m])))",
     "legendFormat": "p50"
    }
   ]
  }
 ]
}