{
 "title": "Exportarr",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Radarr Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "radarr_system_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Movies File Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "radarr_movie_filesize_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Media Storage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "radarr_movie_filesize_total", "legendFormat": "movies" },
    { "expr": "sonarr_series_filesize_bytes", "legendFormat": "shows" },
    { "expr": "lidarr_artists_filesize_bytes", "legendFormat": "music" }
   ]
  },
  {
   "title": "Sonarr Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sonarr_system_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Shows File Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sonarr_series_filesize_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Lidarr Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "radarr_system_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Songs File Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "lidarr_artists_filesize_bytes", "legendFormat": "__auto" }
   ]
  },
  { "title": "Radarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Movies",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "radarr_movie_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Movies Quality",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(radarr_movie_quality_total) by (quality))",
     "legendFormat": "{{quality}}"
    }
   ]
  },
  {
   "title": "Movies Missing",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "radarr_movie_missing_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Movies DL Past Month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(radarr_movie_downloaded_total[30d])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Sonarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Episodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_episode_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Episodes",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_episode_total", "legendFormat": "episodes" },
    { "expr": "sonarr_season_total", "legendFormat": "seasons" },
    { "expr": "sonarr_series_total", "legendFormat": "series" }
   ]
  },
  {
   "title": "Episodes Missing",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_episode_missing_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Episodes DL Past Month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(sonarr_episode_downloaded_total[30d])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Lidarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Songs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lidarr_songs_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Artists by genre",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 19, "x": 5, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(lidarr_artists_genres_total) by (genre))",
     "legendFormat": "{{quality}}"
    }
   ]
  },
  {
   "title": "Songs Missing",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lidarr_songs_missing_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Songs DL Past Month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(lidarr_songs_downloaded_total[30d])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Albums",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lidarr_albums_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Artists",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lidarr_artists_total", "legendFormat": "__auto" }
   ]
  }
 ]
}