---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - helm-release.yaml
  - service-monitor.yaml
configMapGenerator:
  - name: longhorn-grafana-dashboards
    files:
      - dashboard/longhorn-monitor.json
    options:
      labels:
        grafana_dashboard: "1"
